# Generated by Django 2.0.1 on 2018-01-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superheroes',
            old_name='JusticeLeague',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='superheroes',
            old_name='Metahumans',
            new_name='Identity',
        ),
        migrations.RenameField(
            model_name='superheroes',
            old_name='Titans',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='vilains',
            old_name='Cosmic',
            new_name='Hero',
        ),
        migrations.RenameField(
            model_name='vilains',
            old_name='Other',
            new_name='Team',
        ),
        migrations.RemoveField(
            model_name='vilains',
            name='Scientist',
        ),
        migrations.AddField(
            model_name='superheroes',
            name='Power',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
