# Generated by Django 2.0.1 on 2018-01-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0002_auto_20180109_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='vilains',
            name='Name',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
