# Generated by Django 2.0.1 on 2018-01-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superheroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avengers', models.CharField(max_length=100)),
                ('XMen', models.CharField(max_length=100)),
                ('Inhumans', models.CharField(max_length=100)),
                ('Guardians', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vilains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cosmic', models.CharField(max_length=100)),
                ('Other', models.CharField(max_length=100)),
                ('Mutant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marvel.Superheroes')),
            ],
        ),
    ]
