# Generated by Django 2.0.1 on 2018-01-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superheroes',
            old_name='Avengers',
            new_name='Identity',
        ),
        migrations.RenameField(
            model_name='superheroes',
            old_name='Guardians',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='superheroes',
            old_name='Inhumans',
            new_name='Power',
        ),
        migrations.RenameField(
            model_name='superheroes',
            old_name='XMen',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='vilains',
            old_name='Cosmic',
            new_name='Hero',
        ),
        migrations.RenameField(
            model_name='vilains',
            old_name='Other',
            new_name='Team',
        ),
        migrations.RemoveField(
            model_name='vilains',
            name='Mutant',
        ),
    ]
